# Generated by Django 5.1.6 on 2025-03-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptparty',
            name='qr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptparty',
            name='scanned_receipt',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
