# Generated by Django 5.1.6 on 2025-03-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_receiptparty_qr_receiptparty_scanned_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='card',
            name='student',
        ),
        migrations.AddField(
            model_name='receiptparty',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='created_parties', to='main.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptparty',
            name='transaction_acc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='party_transactions', to='main.transactionacc'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentCreatesPartyUsesTransaction',
        ),
    ]
