# Generated by Django 5.1.6 on 2025-03-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_card_bank_remove_card_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptparty',
            name='scanned_receipt',
            field=models.JSONField(null=True),
        ),
    ]
